# Generated by Django 5.2.6 on 2025-10-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='modules',
        ),
    ]
